hm3
ggshchka/2020-2-Atom-QA-Python-S-Saparbekov pull request #3
Opened 2020-10-25 15:40 UTC by ggshchka

# Домашнее задание №3

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* Написаны API тесты
* 
*

2020-10-26 22:40 UTC, snicks92 requested changes

2020-10-26 22:40 UTC, snicks92 commented on hm3/code/api/client.py
> +                                            f'with error "{error}"!')
это тут точно должно быть?

2020-10-26 22:40 UTC, snicks92 commented on hm3/code/tests/test_api.py
> +        )
вынести это в апи клиент?

2020-10-26 22:40 UTC, snicks92 commented on hm3/code/tests/test_api.py
> +    def test_create_and_delete_segment(self, client):
а почему только 1 тест?

2020-10-27 11:03 UTC, ggshchka commented on hm3/code/api/client.py
> +                                            f'with error "{error}"!')
это лишнее, согласен

2020-10-28 14:55 UTC, snicks92 commented
Теперь ок. За то что не уложился в дедлайн - 4 балла из 6

2020-10-28 14:56 UTC, snicks92 approved these changes

2020-10-28 14:56 UTC, merged